<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sarvesh" failures="1" tests="10" name="Free CRM App Test Cases" time="133.762" errors="0" timestamp="2024-03-07T15:03:13 IST">
  <testcase classname="com.crm.qa.testcases.BankMangerLoginTest" name="bankmgerLogintest" time="0.797"/>
  <testcase classname="com.crm.qa.testcases.AddCustomerTest" name="additionofCustomer" time="2.586"/>
  <testcase classname="com.crm.qa.testcases.OpenAccountTest" name="openAccountTestSS" time="3.789"/>
  <testcase classname="com.crm.qa.testcases.Customer_Test" name="CustomerTest" time="11.578"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginTest" name="custLoginTest" time="10.985"/>
  <testcase classname="com.crm.qa.testcases.DepositTest" name="depositProcess" time="13.902"/>
  <testcase classname="com.crm.qa.testcases.WithdrawlTest" name="withdrawlTest" time="14.038"/>
  <testcase classname="com.crm.qa.testcases.TransactionTest" name="TransactionTest" time="15.186"/>
  <testcase classname="com.crm.qa.testcases.LogOutTest" name="logoutTest" time="11.661"/>
  <testcase classname="com.crm.qa.testcases.InavalidAddCustomerTest" name="additionofCustomer" time="3.074">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.crm.qa.pages.InvalidAddustomer.addCustInvalidData(InvalidAddustomer.java:50)
at com.crm.qa.testcases.InavalidAddCustomerTest.additionofCustomer(InavalidAddCustomerTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- additionofCustomer -->
</testsuite> <!-- Free CRM App Test Cases -->
